### ISSUE TITLE
get_product_24hr_stats throw have json exception

### ISSUE THREAD

**Issue by pwong-legendarb** [danpaquin/coinbasepro-python#165]
```
Traceback (most recent call last):
  File "a.py", line 108, in <module>
    s = public_client.get_product_24hr_stats('BTC-USD')
  File "C:\Program Files\Python36\lib\site-packages\gdax\public_client.py", line 215, in get_product_24hr_stats
    return r.json()
  File "C:\Program Files\Python36\lib\site-packages\requests\models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Python36\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Python36\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Python36\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by aaron235** [comment]
I'm getting the same error sporadically with `get_product`ticker`. I think I've determined that the problem comes from a 504 error. It's a bit hard to debug, because you have to wait several hours for the error to come up, but I'm going to try to get to the bottom of it.

**Comment by t8musante** [comment]
I got the same error with `get_time`
