### ISSUE TITLE
JSON error

### ISSUE THREAD

**Issue by rlittman16** [danpaquin/coinbasepro-python#175]
Traceback (most recent call last):
  File "ether1.py", line 32, in <module>
    transaction_to_sell = EtherFunc.CheckSell(list_of_transactions, fraction_gain, public_client)
  File "/home/russell/Desktop/Ethereum/EtherFunc.py", line 54, in CheckSell
    ether_value = public_client.get_product_ticker(product_id='ETH-USD').get('price',0)
  File "/usr/local/lib/python2.7/dist-packages/gdax/public_client.py", line 118, in get_product_ticker
    return r.json()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by mcardillo55** [comment]
These are issues with the GDAX API, but should probably be caught by gdax-python.
