### ISSUE TITLE
 module 'cbpro' has no attribute 'WebsocketClient'

### ISSUE THREAD

**Issue by cyberguilletell** [danpaquin/coinbasepro-python#402]
I try to run this example that appear in the readme
```
# import PyMongo and connect to a local, running Mongo instance
from pymongo import MongoClient
import cbpro
mongo_client = MongoClient('mongodb://localhost:27017/')

# specify the database and collection
db = mongo_client.cryptocurrency_database
BTC_collection = db.BTC_collection

# instantiate a WebsocketClient instance, with a Mongo collection as a parameter
wsClient = cbpro.WebsocketClient(url="wss://ws-feed.pro.coinbase.com", products="BTC-USD",
    mongo_collection=BTC_collection, should_print=False)
wsClient.start()
```

and I got this  error

> AttributeError: module 'cbpro' has no attribute 'WebsocketClient'

I check with the pip freeze and I got his version

cbpro==1.1.4

Even  I try to install direct from de repo
`pip install git+git://github.com/danpaquin/coinbasepro-python.git
`
and continue with the same issue

**Comment by mcardillo55** [comment]
Are you still seeing this? I'm unable to reproduce. I've tried Python 2.7 and 3.8 and I've tried both the pip version and the git version of cbpro.

**Comment by Hechix** [comment]
Hi, i have same error with both WebsocketClient and OrderBook examples from ReadMe.

Stack from the simple Websocket example:

> Traceback (most recent call last):
>   File ".\websocket.py", line 1, in <module>
>     import cbpro
>   File "C:\Users\hechix\AppData\Local\Programs\Python\Python38\lib\site-packages\cbpro\__init__.py", line 3, in <module>
>     from cbpro.websocket_client import WebsocketClient
>   File "C:\Users\hechix\AppData\Local\Programs\Python\Python38\lib\site-packages\cbpro\websocket_client.py", line 15, in <module>
>     from websocket import create_connection, WebSocketConnectionClosedException
>   File "C:\Users\hechix\Documents\python\Coinbase\tests\websocket.py", line 4, in <module>
>     wsClient = cbpro.WebsocketClient(url="wss://ws-feed.pro.coinbase.com",
> AttributeError: partially initialized module 'cbpro' has no attribute 'WebsocketClient' (most likely due to a circular import)

Stack from OrderBook example:
> Traceback (most recent call last):
>   File ".\orderbook.py", line 1, in <module>
>     import cbpro, time
>   File "C:\Users\hechix\AppData\Local\Programs\Python\Python38\lib\site-packages\cbpro\__init__.py", line 3, in <module>
>     from cbpro.websocket_client import WebsocketClient
>   File "C:\Users\hechix\AppData\Local\Programs\Python\Python38\lib\site-packages\cbpro\websocket_client.py", line 15, in <module>
>     from websocket import create_connection, WebSocketConnectionClosedException
>   File "C:\Users\hechix\Documents\python\Coinbase\tests\orderbook.py", line 2, in <module>
>     order_book = cbpro.OrderBook(product_id='BTC-USD')
> AttributeError: partially initialized module 'cbpro' has no attribute 'OrderBook' (most likely due to a circular import)

I have all the packages updated
> Package Version
> ------------------------ ---------
> cbpro 1.1.4
> pymongo 3.5.1
> requests 2.25.0
> requests-oauthlib 1.3.0
> six 1.15.0
> sortedcontainers 2.2.2
> websocket-client 0.40.0

**Comment by Cristianistrate** [comment]
Same issue here, eve with pip install websocket-client==0.40.0
Please advise

**Comment by ianbroad** [comment]
I have the same issue as well.

AttributeError: module 'cbpro' has no attribute 'WebsocketClient'
